---

- block:
    - name: authenticate with cluster
      include_role:
        name: oatakan.openshift-add-auth-config
      vars:
        oc_auth_type: api

    - include_tasks: provision.yml
      when: role_action == 'provision'

    - include_tasks: deprovision.yml
      run_once: yes
      when: role_action == 'deprovision'
  always:
    - name: clear authentication
      include_role:
        name: oatakan.openshift-add-auth-config
      vars:
        oc_auth_type: api
        auth_action: logout