---

- block:
    - name: wait for pvc to be deleted
      k8s_info:
        api_version: v1
        kind: PersistentVolumeClaim
        name: '{{ target_pvc_name }}'
        namespace: '{{ target_namespace }}'
        validate_certs: no
        api_key: "{{ api_key }}"
      register: target_pvc_iso_info
      until: target_pvc_iso_info.resources | length == 0
      no_log: yes
      retries: 10
      delay: 5
  rescue:
    - name: remove finalizer to allow deletion
      community.kubernetes.k8s:
        state: present
        merge_type: merge
        validate_certs: no
        api_key: "{{ api_key }}"
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: '{{ target_pvc_name }}'
            namespace: '{{ target_namespace }}'
            finalizers: null
  when: target_pvc_name is defined