---

- name: wait for disk (dv)
  k8s_info:
    api_version: "{{ api_version_dv }}"
    kind: DataVolume
    name: '{{ template.name }}-disk0'
    namespace: '{{ target_namespace }}'
    verify_ssl: no
    api_key: "{{ api_key }}"
  register: dv_info
  until: (dv_info.resources[0].status.phase | default('')) == 'Succeeded'
  retries: 300
  delay: 5
  ignore_errors: yes