---

- name: Get disk (pvc) info
  k8s_info:
    api_version: v1
    kind: PersistentVolumeClaim
    name: '{{ template.name }}-disk0'
    namespace: '{{ target_namespace }}'
    verify_ssl: no
    api_key: "{{ api_key }}"
  register: pvc_info
  until: (pvc_info.resources[0].metadata.annotations['cdi.kubevirt.io/storage.pod.phase'] | default('')) == 'Succeeded'
  retries: 300
  delay: 5
  ignore_errors: yes