---

- block:
    - name: Get vmi info
      k8s_info:
        api_version: kubevirt.io/v1alpha3
        kind: VirtualMachineInstance
        name: '{{ template.name }}'
        namespace: '{{ target_namespace }}'
        validate_certs: no
        api_key: "{{ api_key }}"
      register: template_vmi
      until: (template_vmi.resources[0].status.nodeName | default('')) | length > 0
      retries: 60
      delay: 3
  rescue:
    - name: stop the vm
      kubevirt_vm:
        state: stopped
        name: '{{ template.name }}'
        namespace: '{{ target_namespace }}'
        validate_certs: no
        api_key: "{{ api_key }}"

    - name: start the vm
      kubevirt_vm:
        state: running
        name: '{{ template.name }}'
        namespace: '{{ target_namespace }}'
        validate_certs: no
        api_key: "{{ api_key }}"

    - name: Get vmi info
      k8s_info:
        api_version: kubevirt.io/v1alpha3
        kind: VirtualMachineInstance
        name: '{{ template.name }}'
        namespace: '{{ target_namespace }}'
        validate_certs: no
        api_key: "{{ api_key }}"
      register: template_vmi
      until: (template_vmi.resources[0].status.nodeName | default('')) | length > 0
      retries: 15
      delay: 3
      ignore_errors: yes

- name: set vmi info
  set_fact:
    new_vmis: '{{ new_vmis | default({}) | combine({template_vmi.resources[0].metadata.name: template_vmi.resources[0]}) }}'

- name: provision service
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'svc.yml') | from_yaml }}"
    validate_certs: no
    api_key: "{{ api_key }}"
  vars:
    owner_uid: "{{ template_vmi.resources[0].metadata.ownerReferences[0].uid | default(None) }}"
  register: template_svc
  when:
    - template.networks is undefined or template.networks | length == 0

- name: provision route
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'route.yml') | from_yaml }}"
    validate_certs: no
    api_key: "{{ api_key }}"
  vars:
    owner_uid: "{{ template_vmi.resources[0].metadata.ownerReferences[0].uid | default(None) }}"
  loop: "{{ template.ports }}"
  loop_control:
    loop_var: port
  when:
    - template.networks is undefined or template.networks | length == 0
    - template.ports | default([]) | length > 0
    - port.route | default(false) | bool

- name: wait for remote port to be available
  wait_for:
    port: "{{ remote_port }}"
    host: "{{ remote_host }}"
    delay: 10
    timeout: "{{ instance_wait_connection_timeout }}"
  connection: local
  when: template_vmi is success
  ignore_errors: yes

- name: wait for remote ip to be available on vmi
  k8s_info:
    api_version: kubevirt.io/v1alpha3
    kind: VirtualMachineInstance
    name: '{{ template.name }}'
    namespace: '{{ target_namespace }}'
    validate_certs: no
    api_key: "{{ api_key }}"
  register: template_vmi
  until: (template_vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0
  retries: "{{ instance_wait_for_ip_retry_limit }}"
  delay: 3
  when: instance_wait_for_ip_retry_limit > 0
  ignore_errors: yes

