apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-clone-to-user
  namespace: {{ template_namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ target_namespace }}
roleRef:
  kind: ClusterRole
  name: {{ kubevirt_clone_cluster_role_name }}
  apiGroup: rbac.authorization.k8s.io