apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: {{ iso_pvc_name }}
  generation: 5
  namespace: {{ target_namespace }}
{% if owner_uid is defined and owner_uid is not none %}
  ownerReferences:
    - apiVersion: kubevirt.io/v1alpha3
      kind: VirtualMachine
      name: {{ template.name }}
      uid: {{ owner_uid }}
      controller: true
      blockOwnerDeletion: true
{% endif %}
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  pvc:
    accessModes:
      - ReadWriteOnce
#      - ReadOnlyMany
#    dataSource: null
    resources:
      requests:
        storage: 20Mi
    storageClassName: {{ pvc_storage_class }}
    volumeMode: Filesystem
  source:
    upload: {}