apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
{% if template.networks is defined and template.networks|length > 0 %}
    k8s.v1.cni.cncf.io/networks: "{{ template.networks | map(attribute='name') | join(', ') }}"
{% endif %}
    kubevirt.io/latest-observed-api-version: v1alpha3
    kubevirt.io/storage-observed-api-version: v1alpha3
    name.os.template.kubevirt.io/rhel8: {{ template.name }}
  name: {{ template.name }}
  generation: 2
  namespace: '{{ target_namespace }}'
  labels:
    app: {{ template.name }}
    app_name: {{ template.app_name }}
    role: {{ template.role }}
    flavor.template.kubevirt.io/medium: 'true'
    vm.kubevirt.io/template: rhel8-server-medium-v0.7.0
    vm.kubevirt.io/template-namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.8.2
    workload.template.kubevirt.io/server: 'true'
    os.family: redhat