---
- name: Playbook to start a openshift virt VM
  hosts: all
  tasks:
  - name: start a VirtualMachine
    kubevirt.core.kubevirt_vm:
      name: phils-test
      namespace: default
      state: present
      running: true
    register: ocp_vm_status
    changed_when: ocp_vm_status.result.status.printableStatus == 'Stopped'
